// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   
    public static final class DriveConstants {
    public static final int kLeftAlphaMotorPort = 3;
    public static final int kLeftBetaMotorPort = 4;
    public static final int kRightAlphaMotorPort = 1;
    public static final int kRightBetaMotorPort = 2; 
    public static final double kDriveDeadband = 0.05; //Slow down the drive speed
    }

    public static final class ElevatorConstants {
    public static final int kLeftElevatorPort = 5;
    public static final int kRightElevatorPort = 6;
    public static final int kCoralShooter = 7;
    

    }

    public static final class OtherConstants{
        public static final double driveTime = 0.5;  //half a second to test DriveABit
        public static final double driveSpeed = 0.6; //slow speed to test DriveABit
        public static final double kElevatorSpeed = 0.05; 
        public static final double kShooterSpeed = 0.05; 
    }
     
}

