// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj.Timer;
import frc.robot.Constants;
//Import required subsystem
import frc.robot.subsystems.DriveTrain;

// NOTE:  Consider using this command inline, rather than writing a subclass.  For more
// information, see:
// https://docs.wpilib.org/en/stable/docs/software/commandbased/convenience-features.html
public class DriveABit extends InstantCommand {
  private final DriveTrain m_drivetrain;
  private final Timer timer = new Timer();
  private double slowDriveTime = Constants.OtherConstants.driveTime;
  private double slowDriveSpeed = Constants.OtherConstants.driveSpeed;

  public DriveABit(DriveTrain subsystem) {
    // Use addRequirements() here to declare subsystem dependencies.
    m_drivetrain = subsystem;
    addRequirements(m_drivetrain);
  }

  // Called when the command is initially scheduled.
  @Override
  public void initialize() {  //set the timer to 0 and start it
    timer.reset();
    timer.start();
  }
   // Called every time the scheduler runs while the command is scheduled.
   @Override
   public void execute() {
    m_drivetrain.tankDrive(slowDriveSpeed,slowDriveSpeed); //drive slowly but not so slow we don't move
   }

   // Called once the command ends or is interrupted.
   @Override
   public void end(boolean interrupted) {
    m_drivetrain.tankDrive(0,0);
   }

   // Returns true when the command should end.
   @Override
   public boolean isFinished() {
       return timer.get() >= slowDriveTime;
   }

   @Override
   public boolean runsWhenDisabled() {
       // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
       return false;

   // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
   }
}
